data:
    name: 'hpatches' #hpatches
    data_dir: './data/hpatches' #./data/hpatches
    export_dir_root : './data/hpatches_val/'
    experiment_name : 'EX6.superpoint_bn_index_coco_loss0.5/' # TODO
    export_dir: 'repeatibility/hpatches/'
    alteration: 'v'  # 'all' 'i' 'v' TODO
    preprocessing:
        resize: [240,320]
    homography_adaptation:
        num: 0
        aggregation: 'sum'
        filter_counts: 0
        homographies:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.1
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            allow_artifacts: true
            patch_ratio: 0.5
model:
    name: 'superpoint_bn_index' #superpoint_bn_rawï¼Œsuperpoint_bn_index
    using_bn: true
    pretrained_model: './export/5.superpoint_bn_index_coco_loss_0.5/SBIC_7_29571.pth'
    grid_size: 8
    backbone:
        backbone_type: 'VGG'
        vgg:
            channels: [64,64,64,64,128,128,128,128]
    det_head: #detector head
        feat_in_dim: 128
    des_head: #descriptor head
        feat_in_dim: 128
        feat_out_dim: 256
    learning_rate: 0.001
    nms: 4
    topk: 1000
    det_thresh: 0.001 # 0.001
    #batch_size: 50
    #eval_batch_size: 50

